### ISSUE TITLE
Clarify query parameter names

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/old-query-tool#285]
While we are still only handling non-session-level phenotypic information, we should update the names of the query parameters in the UI accordingly so there is no confusion about which timepoint users are querying for.

These include:
"Min/max age" -> "Min/max age at baseline"
"Diagnosis" -> "Diagnosis at baseline"
"Minimum number of sessions" -> "Minimum number of imaging sessions"

- See also https://github.com/neurobagel/bagel-cli/issues/225

TODO
- [x] have on-hover tooltip for each query parameter

**Comment by rmanaem** [comment]
@neurobagel/dev There is one issue with adding a tooltip for diagnosis. Since we already have a tooltip for healthy control and because the healthy control checkbox is implemented as part of the diagnosis categorical component, when we hover over the healthy control checkbox both tooltips get rendered


![Image](https://github.com/neurobagel/query-tool/assets/77515879/420a8f52-1f5f-4cbe-8429-27b7c290a553)


Are we okay with merging the two?

**Comment by rmanaem** [comment]
@surchs Could you add a drawing of what you mentioned during stand-up?

**Comment by surchs** [comment]
something like this:
![image](https://github.com/neurobagel/query-tool/assets/1302022/4b52794c-8406-4be1-b15d-747eb484f936)

1. add horizontal dividers to visually differentiate two new sections (pheno and imaging)
2. move all pheno things to pheno section, and all imaging things to imaging section (modality and # sessions)
3. add one disclaimer at the top of the pheno session that all variables are taken at baseline session
